version: '3.8'

services:
  zink-api:
    build:
      context: ../api
    ports:
      - "8000:8000"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_URI=${MONGO_URI}
      - SIGNING_KEY=${SIGNING_KEY}
      - AUTH_KEY=${AUTH_KEY}
      - RUNTIME_ENV=${RUNTIME_ENV}
      - GIN_MODE=${GIN_MODE}
