services:
  zink-api:
    image: elshaddai/zink-api:main
    expose:
      - 8000
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_URI=${MONGO_URI}
      - SIGNING_KEY=${SIGNING_KEY}
      - AUTH_KEY=${AUTH_KEY}
      - RUNTIME_ENV=${RUNTIME_ENV}
      - GIN_MODE=${GIN_MODE}
  zink-web:
    image: elshaddai/zink-web:main
    expose:
      - 3000
    environment:
      - API_URL=http://zink-api:8000
    depends_on:
      - zink-api
  nginx:
    image: nginx:alpine
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs:/etc/nginx/certs
    depends_on:
      - zink-web
      - zink-api
