services:
  zink-api:
    image: elshaddai/zink-api:main
    expose:
      - 8000
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_URI=${MONGO_URI}
      - SIGNING_KEY=${SIGNING_KEY}
      - AUTH_KEY=${AUTH_KEY}
      - RUNTIME_ENV=${RUNTIME_ENV}
      - GIN_MODE=${GIN_MODE}
  zink-web:
    image: elshaddai/zink-web:main
    expose:
      - 3000
    environment:
      - API_URL=http://zink-api:8000
      - GOOGLE_ACCOUNT_KEY_FILE_PATH=/etc/secrets/google_account_key.json
      - GOOGLE_ANALYTICS_PROPERTY=${GOOGLE_ANALYTICS_PROPERTY}
      - GEONAME_USERNAME=${GEONAME_USERNAME}
    volumes:
      - ../secrets:/etc/secrets:ro
    depends_on:
      - zink-api
  nginx:
    image: nginx:alpine
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - DOMAIN_NAME=${DOMAIN_NAME}
      - BLOB_DOMAIN_NAME=${BLOB_DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx:/etc/nginx/templates
      - ../certs:/etc/nginx/certs
      - /var/www/blobs:/var/www/blobs
    depends_on:
      - zink-web
      - zink-api
